// Refreshes the Calendar's public holidays from Google's public holiday
// calendars and writes a migration that replaces the `holidays` table rows.
//
//   node tool/refresh_holidays.mjs
//   supabase db push --linked
//
// Run it about once a year (Google publishes several years ahead).
import { writeFileSync } from 'node:fs';

const REGIONS = {
  in: 'en.indian', us: 'en.usa', uk: 'en.uk', ca: 'en.canadian', au: 'en.australian',
  ae: 'en.ae', sg: 'en.singapore', de: 'en.german', fr: 'en.french', jp: 'en.japanese',
};
const FROM_YEAR = new Date().getFullYear() - 1;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const unesc = (v) => v.replace(/\\n/g, '\n').replace(/\\,/g, ',').replace(/\;/g, ';').replace(/\\\\/g, '\\');

function parse(ics) {
  const lines = ics.replace(/\r\n[ \t]/g, '').replace(/\r/g, '').split('\n');
  const out = []; let ev = null;
  for (const line of lines) {
    if (line === 'BEGIN:VEVENT') ev = {};
    else if (line === 'END:VEVENT' && ev) {
      if (ev.date && ev.name) out.push({ date: ev.date, name: ev.name, type: (ev.desc ?? '').startsWith('Public holiday') ? 'public' : 'observance' });
      ev = null;
    } else if (ev) {
      const m = line.match(/^DTSTART(?:;[^:]*)?:(\d{4})(\d{2})(\d{2})/);
      if (m) ev.date = `${m[1]}-${m[2]}-${m[3]}`;
      else if (line.startsWith('SUMMARY:')) ev.name = unesc(line.slice(8)).trim().slice(0, 200);
      else if (line.startsWith('DESCRIPTION:')) ev.desc = unesc(line.slice(12));
    }
  }
  return out;
}

const q = (s) => `'${s.replace(/'/g, "''")}'`;
const rows = [];
for (const [code, id] of Object.entries(REGIONS)) {
  const url = `https://calendar.google.com/calendar/ical/${encodeURIComponent(`${id}#holiday@group.v.calendar.google.com`)}/public/basic.ics`;
  let res;
  for (let attempt = 0; attempt < 4; attempt++) {
    res = await fetch(url);
    if (res.status !== 429) break;
    await sleep(5000 * (attempt + 1));
  }
  if (!res.ok) { console.error(`${code}: HTTP ${res.status}, skipped`); continue; }
  const seen = new Set();
  const list = parse(await res.text()).filter((h) => {
    const k = `${h.date}|${h.name}`;
    if (seen.has(k) || Number(h.date.slice(0, 4)) < FROM_YEAR) return false;
    seen.add(k); return true;
  });
  for (const h of list) rows.push(`(${q(code)}, ${q(h.date)}, ${q(h.name)}, ${q(h.type)})`);
  console.log(`${code}: ${list.length} days`);
  await sleep(1500);
}
if (!rows.length) throw new Error('nothing fetched');

const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
const file = `supabase/migrations/${stamp}_refresh_holidays.sql`;
writeFileSync(file, `-- Generated by tool/refresh_holidays.mjs from Google's public holiday calendars.
delete from public.holidays;
insert into public.holidays (region, date, name, type) values
${rows.join(',\n')}
on conflict do nothing;
`);
console.log(`wrote ${file} (${rows.length} rows)`);
